src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 * @UniqueEntity(fields={"phone"}, message="Such phone number has already been used")
 * @UniqueEntity(fields={"email"}, message="Such phone email has already been used")
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32)
     * @Assert\NotBlank(message="Name field can not be empty!")
     * @Assert\Length(
     *      min = 2,
     *      max = 32,
     *      minMessage = "The name is too short. Minimum length is {{ limit }} characters",
     *      maxMessage = "The name cannot be longer than {{ limit }} characters"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=32)
     * @Assert\NotBlank(message="Surname field can not be empty!")
     * @Assert\Length(
     *      min = 2,
     *      max = 32,
     *      minMessage = "The surname is too short. Minimum length is {{ limit }} characters",
     *      maxMessage = "The surname cannot be longer than {{ limit }} characters"
     * )
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=24)
     * @Assert\NotBlank(message="Phone field can not be empty!")
     * @Assert\Length(
     *      min = 5,
     *      max = 32,
     *      minMessage = "The phone is too short. Minimum length is {{ limit }} characters",
     *      maxMessage = "The phone cannot be longer than {{ limit }} characters"
     * )
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank(message="Email field can not be empty!")
     * @Assert\Length(
     *      min = 5,
     *      max = 32,
     *      minMessage = "The email is too short. Minimum length is {{ limit }} characters",
     *      maxMessage = "The email cannot be longer than {{ limit }} characters"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Text field can not be empty!")
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Company id field cannot have zero or negative amount of pages")
     * @Assert\Type(
     *     type="integer",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     */
    private $company_id;

    /**
     * @ORM\ManyToOne(targetEntity=Company::class, inversedBy="customers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCompanyId(): ?int
    {
        return $this->company_id;
    }

    public function setCompanyId(int $company_id): self
    {
        $this->company_id = $company_id;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use App\Entity\Company;
use App\Entity\Customer;

class CustomerController extends AbstractController
{
    /**
     * @Route("/customer", name="customer_index", methods={"GET"})
     */
    public function index(Request $r): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $companies =  $this->getDoctrine()
        ->getRepository(Company::class)
        ->findAll();
        
        $customers = $this->getDoctrine()
        ->getRepository(Customer::class);

       
        if($r->query->get('filter') == 0 ){
            $customers= $customers->findAll();
            
        }else{
            $customers = $customers->findBy(['company_id'=> $r->query->get('filter')], ['surname' => 'asc']);
        }

        return $this->render('customer/index.html.twig', [
            'customers'=>$customers,
            'companies' => $companies,
            'companyID'=>$r->query->get('filter') ?? 0,
            'errors' => $r->getSession()->getFlashBag()->get('errors', []),
            'success' => $r->getSession()->getFlashBag()->get('success', [])
        ]);
    }

    /**
     * @Route("/customer/create", name="customer_create", methods={"GET"})
     */
    public function create(Request $r): Response
    {

        $companies =  $this->getDoctrine()
        ->getRepository(Company::class)
        ->findAll();

        if(empty($companies)){
            $r->getSession()->getFlashBag()->add('errors', 'You cant create a customer because there are no companies');
            $r->getSession()->getFlashBag()->add('errors', 'Create a new company');
            return $this->redirectToRoute('company_create');
        }
        
        $customer_name= $r->getSession()->getFlashBag()->get('customer_name', []);
        $customer_surname = $r->getSession()->getFlashBag()->get('customer_surname', []);
        $customer_phone = $r->getSession()->getFlashBag()->get('customer_phone', []);
        $customer_email = $r->getSession()->getFlashBag()->get('customer_email', []);
        $customer_comment = $r->getSession()->getFlashBag()->get('customer_comment', []);
        $customer_company = $r->getSession()->getFlashBag()->get('customer_company_id');
       
        
        return $this->render('customer/create.html.twig', [
            'customer_name' => $customer_name[0] ?? '',
            'customer_surname' => $customer_surname[0] ?? '',
            'customer_phone' => $customer_phone[0] ?? '',
            'customer_email' => $customer_email[0] ?? '',
            'customer_comment' => $customer_comment[0] ?? '',
            'customer_company' => $customer_company,
            'companies' => $companies,
            'errors' => $r->getSession()->getFlashBag()->get('errors', []),
            'success' => $r->getSession()->getFlashBag()->get('success', []),
        ]);
    }

     /**
     * @Route("/customer/create", name="customer_store", methods={"POST"})
     */
    public function store(Request $r, ValidatorInterface $validator): Response
    {
        $submittedToken = $r->request->get('token');

        if (!$this->isCsrfTokenValid('check_csrf_hidden', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Bad talken CSRF');
            return $this->redirectToRoute('customer_create');
        }

        $company =  $this->getDoctrine()
        ->getRepository(Company::class)
        ->find($r->request->get('customer_company_id'));

        if($company == null){
            $r->getSession()->getFlashBag()->add('errors', 'Choose company from the list');
        }

        $customer = new Customer;

        $customer->
        setName($r->request->get('customer_name'))->
        setSurname($r->request->get('customer_surname'))->
        setPhone($r->request->get('customer_phone'))->
        setEmail($r->request->get('customer_email'))->
        setComment($r->request->get('customer_comment'))->
        setCompany($company);

        $errors = $validator->validate($customer);
        if (count($errors) > 0){
            foreach($errors as $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }
            $r->getSession()->getFlashBag()->add('note_title', $r->request->get('note_title'));
            $r->getSession()->getFlashBag()->add('note_priority', $r->request->get('note_priority'));
            $r->getSession()->getFlashBag()->add('note_note', $r->request->get('note_note'));
            $r->getSession()->getFlashBag()->add('note_status_id', $r->request->get('note_status_id'));
            return $this->redirectToRoute('customer_create');
        }
        if(null === $company) {
            return $this->redirectToRoute('customer_create');
        }


        //creating entity manager sending data to database
        $entityManager = $this->getDoctrine()->getManager();
        //organizing data to be send
        $entityManager->persist($customer);
        //wrting
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Customer was successfully created');

        return $this->redirectToRoute('customer_index');
    }

    /**
     * @Route("/customer/edit/{id}", name="customer_edit", methods= {"GET"})
     */
    public function edit(Request $r, int $id): Response
    {
        $customer = $this->getDoctrine()
        ->getRepository(Customer::class)
        ->find($id);

        $companies =  $this->getDoctrine()
        ->getRepository(Company::class)
        ->findAll();
        
        return $this->render('customer/edit.html.twig', [
            'customer' => $customer,
            'companies' => $companies,
            'errors' => $r->getSession()->getFlashBag()->get('errors', []),
            'success' => $r->getSession()->getFlashBag()->get('success', []),
        ]);
    }

    /**
     * @Route("/customer/update/{id}", name="customer_update", methods= {"POST"})
     */
    public function update(Request $r, int $id, ValidatorInterface $validator): Response
    {
        $submittedToken = $r->request->get('token');


        $customer = $this->getDoctrine()
        ->getRepository(Customer::class)
        ->find($id);

        if (!$this->isCsrfTokenValid('check_csrf_hidden', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Bad talken CSRF');
            return $this->redirectToRoute('customer_edit' , ['id'=>$customer->getId()]);
        }
        
        $company =  $this->getDoctrine()
        ->getRepository(Company::class)
        ->find($r->request->get('customer_company_id'));

        $customer->
        setName($r->request->get('customer_name'))->
        setSurname($r->request->get('customer_surname'))->
        setPhone($r->request->get('customer_phone'))->
        setEmail($r->request->get('customer_email'))->
        setComment($r->request->get('customer_comment'))->
        setCompany($company);

        $errors = $validator->validate($customer);
        if (count($errors) > 0){
            foreach($errors as $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }
            return $this->redirectToRoute('note_edit', ['id'=>$customer->getId()] );
        }

        //creating entity manager sending data to database
        $entityManager = $this->getDoctrine()->getManager();
        //organizing data to be send
        $entityManager->persist($customer);
        //wrting
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Customer was successfully edited');

        return $this->redirectToRoute('customer_index');
    }

    /**
     * @Route("/customer/delete/{id}", name="customer_delete", methods= {"POST"})
     */
    public function delete(Request $r, int $id): Response
    {
        $submittedToken = $r->request->get('token');

        if (!$this->isCsrfTokenValid('check_csrf_hidden', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Bad talken CSRF');
            return $this->redirectToRoute('customer_index');
        }

        $customer = $this->getDoctrine()
        ->getRepository(Customer::class)
        ->find($id);

        //creating entity manager sending data to database
        $entityManager = $this->getDoctrine()->getManager();
        //organizing data to be send
        $entityManager->remove($customer);
        //wrting
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Customer was successfully deleted');

        return $this->redirectToRoute('customer_index');
    }
}

templates/customer/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create new Customer
{% endblock %}

{% block body %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div>
					<div>
						<h1>Create new Customer </h1>
					</div>

					<div>
						<form action="{{path('customer_store')}}" method="POST">
							<div class="form-group">
								<label>Name:</label>
								<input type="text" class="form-control" name="customer_name" value="{{customer_name}}">
								<small class="form-text text-muted">Customer name.</small>
							</div>
							<div class="form-group">
								<label>Surname:</label>
								<input type="text" class="form-control" name="customer_surname" value="{{customer_surname}}">
								<small class="form-text text-muted">Customer surname.</small>
							</div>
							<div class="form-group">
								<label>Phone:</label>
								<input type="text" class="form-control" name="customer_phone" value="{{customer_phone}}">
								<small class="form-text text-muted">Customer phone number.</small>
							</div>
							<div class="form-group">
								<label>Email:</label>
								<input type="text" class="form-control" name="customer_email" value="{{customer_email}}">
								<small class="form-text text-muted">Customer email address.</small>
							</div>
                            <div class="form-group">
								<label>Comment:</label>
                                <textarea name="customer_comment" id="summernote">{{customer_comment|raw}}</textarea>
							</div>
                            <div class="form-group">
								<label>Company:</label>
                                <select name="customer_company_id" class="form-control">
									<option value="0">Select company</option>
									{% for company in companies %}
										<option value="{{company.id}}" {% if company.id == customer_company %}selected{% endif %}>UAB " {{company.uab}} "</option>
									{% endfor %}
								</select>
								<small class="form-text text-muted">Available companies.</small>
							</div>
							<input type="hidden" name="token" value="{{ csrf_token('check_csrf_hidden') }}"/>
							<button type="submit" class="btn btn-dark btn-add save-btn btn-block">Add new Customer</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

templates/customer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modify Customer Data
{% endblock %}

{% block body %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div>
					<div>
						<h1>Modify Customer Data</h1>
					</div>

					<div>
                        <form action="{{path('customer_update', {id: customer.id})}}" method="POST">
							<div class="form-group">
								<label>Name:</label>
								<input type="text" class="form-control" name="customer_name" value="{{customer.name}}">
								<small class="form-text text-muted">Customer name.</small>
							</div>
                            <div class="form-group">
								<label>Surname:</label>
								<input type="text" class="form-control" name="customer_surname" value="{{customer.surname}}">
								<small class="form-text text-muted">Customer surname.</small>
							</div>
                            <div class="form-group">
								<label>Phone:</label>
								<input type="text" class="form-control" name="customer_phone" value="{{customer.phone}}">
								<small class="form-text text-muted">Customer phone number.</small>
							</div>
							<div class="form-group">
								<label>Email:</label>
								<input type="text" class="form-control" name="customer_email" value="{{customer.email}}">
								<small class="form-text text-muted">Customer email address.</small>
							</div>
                            <div class="form-group">
								<label>Comment:</label>
                                <textarea name="customer_comment" id="summernote">{{customer.comment|raw}}</textarea>
							</div>
                            <div class="form-group">
								<label>Company:</label>
                                <select name="customer_company_id" class="form-control">
									<option value="0">Select company</option>
									{% for company in companies %}
										<option value="{{company.id}}" {% if company.id == customer.companyId %}selected{% endif %}>UAB " {{company.uab}} "</option>
									{% endfor %}
								</select>
								<small class="form-text text-muted">Available companies.</small>
							</div>
							<input type="hidden" name="token" value="{{ csrf_token('check_csrf_hidden') }}"/>
							<button type="submit" class="btn btn-dark btn-add save-btn btn-block">Edit Customer</button>
						</form>
						
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	List of Customers
{% endblock %}


{% block body %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div>
					<div>
						<h1>List  of Customers</h1>
					</div>
					{% if customers|length == 0 %}
						<div class="margin-top"></div>
						<div class="row justify-content-center">
							<h3 style="width:100%;text-align:center;">Your list of customers is empty</h3>
							<p>Go to:</p>
							<a class="btn btn-dark btn-add save-btn btn-block" href="{{ path('customer_create') }}">
								Create a customer
							</a>
						</div>
					{% else %}
						<div>
							List order by:
							<form action="{{ path('customer_index')}}" method="GET" class="sort-form">
								<div class="btn-group order-by">
									<select name="filter" class="btn btn-outline-dark dropdown-toggle">
										<option value="0">All</option>
										{% for company in companies %}
											<option value="{{company.id}}" {% if companyID == company.id %} selected {% endif %}>UAB " {{company.uab}} "</option>
										{% endfor %}
									</select>
									<button type="submit" class="btn btn-sort">Firlter IT!</button>
									<a href="{{ path('customer_index')}}" class="btn btn-sort">
										<i class="fa fa-eraser" aria-hidden="true"></i>
									</a>
								</div>
							</form>
							<ul class="list-group unordered-list ">
								{% for customer in customers %}
									<li class=" li-bck" style="background:transparent;">
										<div class="list-group-item__line single-element info-list">
											<span>
												<div class="single-element">
													{{customer.name}}
													{{customer.surname}}
												</div>
											</span>
											<div class="list-group-item__line__buttons">
												<a href="{{ path('customer_edit', {id: customer.id}) }}" class="btn-edit btn">
													<i class="fa fa-plus" aria-hidden="true"></i>
												</a>
												<form action="{{ path('customer_delete', {id: customer.id}) }}" method="POST">
													<input type="hidden" name="token" value="{{ csrf_token('check_csrf_hidden') }}"/>
													<button type="submit" class="btn-delete btn">
														<i class="fa fa-trash" aria-hidden="true"></i>
													</button>
												</form>
											</div>
										</div>
										<div class="list-group-item__line single-element">
											<div class="single-element list-group-item__line">
												Phone Number :
												{{customer.phone}}
											</div>
										</div>
										<div class="list-group-item__line single-element">
											<div class="single-element list-group-item__line">
												Email Address :
												{{customer.email}}
											</div>
										</div>
										<div class="list-group-item__line single-element">
											<div class="single-element list-group-item__line">
												{% for company in companies %}
													{% if company.id == customer.companyId %}
														Working Company: UAB "
														{{company.uab}}
														"
													{% endif %}
												{% endfor %}
											</div>
										</div>
										<div class="list-group-item__line single-element">
											<div class="single-element list-group-item__line">
												Comment:
												{{customer.comment|raw}}
											</div>
										</div>

									</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}